<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="testCases.DataServices.Login_Sucessful" tests="1" time="1.538" ignored="0" failures="0" timestamp="15 Nov 2019 10:32:45 GMT" skipped="0" hostname="LAP06589" errors="1">
  <testcase name="Login_Sucessful" time="1.538" classname="testCases.DataServices.Login_Sucessful">
    <error type="java.lang.RuntimeException" message="A unique test has not been found - add additional or remove match criteria EnternalTests ln178">
      <![CDATA[java.lang.RuntimeException: A unique test has not been found - add additional or remove match criteria EnternalTests ln178
	at alm.qc.restapi.MF_Assert.assertTrue(SourceFile:15)
	at alm.qc.restapi.ExternalTests.uploadTestRun(SourceFile:181)
	at alm.qc.restapi.ExternalTests.uploadTestRun(SourceFile:423)
	at resources.base.WebBase.QcExecution(WebBase.java:798)
	at frameworkCore.ComponentDriver.Executekeywords(ComponentDriver.java:69)
	at testCases.DataServices.Login_Sucessful.Login_Sucessful(Login_Sucessful.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Login_Sucessful -->
</testsuite> <!-- testCases.DataServices.Login_Sucessful -->
